#!/usr/bin/env node

const { execSync, spawnSync } = require('child_process');
const os = require('os');

const repository = execSync('git rev-parse --show-toplevel', { encoding: 'utf-8' }).trim();
const npm = os.platform() === 'win32' ? 'npm.cmd' : 'npm';

const res = spawnSync(npm, ['run', 'pre-commit'], { cwd: repository, stdio: 'inherit', encoding: 'utf-8' });

if (res.error) {
    console.error(res.error);
    process.exit(1);
}

process.exit(res.status);
