packages:
  - packages/*

catalog:
  '@jest/globals': ^30.2.0
  '@jest/types': ^30.2.0
  '@swc/jest': ^0.2.39
  '@testing-library/dom': ^10.4.1
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.1
  '@testing-library/user-event': ^14.6.1
  '@types/node': ^22.19.3
  '@types/react': ^18.3.27
  '@types/react-dom': ^18.3.7
  '@types/semver': ^7.7.1
  '@types/text-table': ^0.2.5
  '@types/yargs-parser': ^21.0.3
  '@typescript-eslint/eslint-plugin': ^8.51.0
  '@typescript-eslint/parser': ^8.51.0
  '@vitejs/plugin-react': ^5.1.2
  browserslist: ^4.28.1
  camelcase: ^9.0.0
  chalk: ^5.6.2
  clsx: ^2.1.1
  concurrently: ^9.2.1
  cross-env: ^10.1.0
  dayjs: ^1.11.19
  electron: 39.2.7
  electron-builder: ^26.4.0
  electron-devtools-installer: ^4.0.0
  electron-store: ^11.0.2
  esbuild-loader: ^4.4.2
  eslint: ^9.39.2
  eslint-config-airbnb: ^19.0.4
  eslint-config-airbnb-base: ^15.0.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-import: ^2.32.0
  eslint-plugin-jest: ^29.12.1
  eslint-plugin-jsx-a11y: ^6.10.2
  eslint-plugin-n: ^17.23.1
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  fork-ts-checker-webpack-plugin: ^9.1.0
  husky: ^9.1.7
  identity-obj-proxy: ^3.0.0
  jest: ^30.2.0
  jest-environment-jsdom: ^30.2.0
  jest-watch-typeahead: ^3.0.1
  lint-staged: ^16.2.7
  postcss: ^8.5.6
  prettier: 3.7.4
  react: ^18.3.1
  react-dom: ^18.3.1
  react-router: ^7.11.0
  rimraf: ^6.1.2
  sass: ^1.97.1
  semver: ^7.7.3
  source-map-loader: ^5.0.0
  stylelint: ^16.26.1
  stylelint-config-recess-order: ^7.4.0
  stylelint-config-sass-guidelines: ^12.1.0
  stylelint-config-standard: ^39.0.1
  stylelint-config-standard-scss: ^16.0.0
  stylelint-order: ^7.0.1
  text-table: ^0.2.0
  typescript: 5.9.3
  typescript-plugin-css-modules: ^5.2.0
  vite: ^7.3.0
  vite-plugin-checker: ^0.12.0
  vite-tsconfig-paths: ^6.0.3
  web-vitals: ^5.1.0
  webpack: ^5.104.1
  webpack-cli: ^6.0.1
  whatwg-fetch: ^3.6.20
  winston: ^3.19.0
  yargs-parser: ^22.0.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - less
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - electron
  - electron-winstaller
  - esbuild

publicHoistPattern:
  - '*eslint*'

workspaceConcurrency: 0
