packages:
  - packages/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - unrs-resolver

onlyBuiltDependencies:
  - '@swc/core'
  - electron
  - electron-winstaller
  - esbuild

publicHoistPattern:
  - '*eslint*'

workspaceConcurrency: 0
