// Type definitions from @types/node@12.19.9, used for Nodejs v12
/* eslint-disable import/newline-after-import */
/* eslint-disable @typescript-eslint/naming-convention */

import crypto, {
    BasePrivateKeyEncodingOptions,
    BinaryLike,
    CipherCCM,
    CipherCCMOptions,
    CipherCCMTypes,
    CipherGCM,
    CipherGCMOptions,
    CipherGCMTypes,
    CipherKey,
    DSAEncoding,
    DSAKeyPairKeyObjectOptions,
    DSAKeyPairOptions,
    DecipherCCM,
    DecipherGCM,
    ECKeyPairKeyObjectOptions,
    ECKeyPairOptions,
    ED25519KeyPairKeyObjectOptions,
    ED25519KeyPairOptions,
    ED448KeyPairKeyObjectOptions,
    ED448KeyPairOptions,
    HashOptions,
    KeyExportOptions,
    KeyPairKeyObjectResult,
    KeyPairSyncResult,
    PrivateKeyInput,
    PublicKeyInput,
    RSAKeyPairKeyObjectOptions,
    RSAKeyPairOptions,
    RsaPrivateKey,
    RsaPublicKey,
    VerifyKeyObjectInput,
    VerifyPublicKeyInput,
    X25519KeyPairKeyObjectOptions,
    X25519KeyPairOptions,
    X448KeyPairKeyObjectOptions,
    X448KeyPairOptions,
} from 'crypto';
export type {
    BasePrivateKeyEncodingOptions,
    BinaryLike,
    CipherCCM,
    CipherCCMOptions,
    CipherCCMTypes,
    CipherGCM,
    CipherGCMOptions,
    CipherGCMTypes,
    CipherKey,
    DSAEncoding,
    DSAKeyPairKeyObjectOptions,
    DSAKeyPairOptions,
    DecipherCCM,
    DecipherGCM,
    ECKeyPairKeyObjectOptions,
    ECKeyPairOptions,
    ED25519KeyPairKeyObjectOptions,
    ED25519KeyPairOptions,
    ED448KeyPairKeyObjectOptions,
    ED448KeyPairOptions,
    HashOptions,
    KeyExportOptions,
    KeyPairKeyObjectResult,
    KeyPairSyncResult,
    PrivateKeyInput,
    PublicKeyInput,
    RSAKeyPairKeyObjectOptions,
    RSAKeyPairOptions,
    RsaPrivateKey,
    RsaPublicKey,
    VerifyKeyObjectInput,
    VerifyPublicKeyInput,
    X25519KeyPairKeyObjectOptions,
    X25519KeyPairOptions,
    X448KeyPairKeyObjectOptions,
    X448KeyPairOptions,
};

const _ = window.require('crypto') as typeof crypto;
export default _;

const {
    Certificate,
    Cipher,
    Decipher,
    DiffieHellman,
    ECDH,
    Hash,
    Hmac,
    KeyObject,
    Signer,
    Verify,
    constants,
} = _;
export {
    Certificate,
    Cipher,
    Decipher,
    DiffieHellman,
    ECDH,
    Hash,
    Hmac,
    KeyObject,
    Signer,
    Verify,
    constants,
};
