// Type definitions from @types/node@12.19.9, used for Nodejs v12
/* eslint-disable import/newline-after-import */

import child_process, {
    ChildProcess,
    ChildProcessByStdio,
    ChildProcessWithoutNullStreams,
    CommonOptions,
    ExecException,
    ExecFileOptions,
    ExecFileOptionsWithBufferEncoding,
    ExecFileOptionsWithOtherEncoding,
    ExecFileOptionsWithStringEncoding,
    ExecFileSyncOptions,
    ExecFileSyncOptionsWithBufferEncoding,
    ExecFileSyncOptionsWithStringEncoding,
    ExecOptions,
    ExecOptionsWithBufferEncoding,
    ExecOptionsWithStringEncoding,
    ExecSyncOptions,
    ExecSyncOptionsWithBufferEncoding,
    ExecSyncOptionsWithStringEncoding,
    ForkOptions,
    MessageOptions,
    ProcessEnvOptions,
    PromiseWithChild,
    SpawnOptions,
    SpawnOptionsWithStdioTuple,
    SpawnOptionsWithoutStdio,
    SpawnSyncOptions,
    SpawnSyncOptionsWithBufferEncoding,
    SpawnSyncOptionsWithStringEncoding,
    SpawnSyncReturns,
    StdioNull,
    StdioOptions,
    StdioPipe,
} from 'child_process';
export type {
    ChildProcess,
    ChildProcessByStdio,
    ChildProcessWithoutNullStreams,
    CommonOptions,
    ExecException,
    ExecFileOptions,
    ExecFileOptionsWithBufferEncoding,
    ExecFileOptionsWithOtherEncoding,
    ExecFileOptionsWithStringEncoding,
    ExecFileSyncOptions,
    ExecFileSyncOptionsWithBufferEncoding,
    ExecFileSyncOptionsWithStringEncoding,
    ExecOptions,
    ExecOptionsWithBufferEncoding,
    ExecOptionsWithStringEncoding,
    ExecSyncOptions,
    ExecSyncOptionsWithBufferEncoding,
    ExecSyncOptionsWithStringEncoding,
    ForkOptions,
    MessageOptions,
    ProcessEnvOptions,
    PromiseWithChild,
    SpawnOptions,
    SpawnOptionsWithStdioTuple,
    SpawnOptionsWithoutStdio,
    SpawnSyncOptions,
    SpawnSyncOptionsWithBufferEncoding,
    SpawnSyncOptionsWithStringEncoding,
    SpawnSyncReturns,
    StdioNull,
    StdioOptions,
    StdioPipe,
};

const _ = window.require('child_process') as typeof child_process;
export default _;
