name: Regular Jobs

on:
  push:
    branches:
      - '**'
      - '!docs/*'
      - '!skill/*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PNPM environment
        uses: pnpm/action-setup@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Build application
        run: pnpm run build

      - name: Do typecheck
        run: pnpm run typecheck

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PNPM environment
        uses: pnpm/action-setup@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PNPM environment
        uses: pnpm/action-setup@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install

      - name: Do coverage test
        run: pnpm run test:jsdom --coverage && pnpm run test:node --coverage
